name: Build and Zip Astro Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'  # This enables caching of the pnpm store

      - name: Install pnpm
        run: npm install -g pnpm@latest  # Or specify a version like pnpm@9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Astro project
        run: pnpm run build

      - name: Zip build output
        run: zip -r build-artifact.zip dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: astro-build-zip
          path: build-artifact.zip
